name: Build SDK package

on:
  workflow_dispatch:

jobs:
  build_sdk:
    runs-on: self-hosted
    steps:
      - name: Checkout code with caching for Git LFS
        uses: nschloe/action-cached-lfs-checkout@v1.1.2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install package with dev and notebook requirements
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,notebooks]"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package contents
        run: twine check dist/*

      - name: Upload wheel and source files
        # Publish the built wheel and source tarball to github
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: dist
          path: dist
