name: Publish package [TestPyPI]

on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-package.yaml
    secrets:
      PYPI_USER: ${{ secrets.TEST_PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      PYPI_HOST: test.pypi.org
