name: Pre-merge tests

# Controls when the action will run. This action can be triggered manually
# (workflow_dispatch trigger), and it will be run automatically when a PR to main is made.
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - "releases/**"


permissions: {} # No permissions by default

jobs:
  semgrep-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run Semgrep scan
        uses: open-edge-platform/geti-ci/actions/semgrep@23728dd504fea31281592417e51496e92ba220fe
        with:
          scan-scope: "changed"
          severity: "LOW"
          fail-on-findings: true
          output-format: "sarif"
