name: Nightly tests [SC v1.1]

on:
  workflow_dispatch: # run on request (no need for PR)

  schedule: # Execute tests at midnight every day
    - cron: "0 0 * * *"

jobs:
  build:
    uses: ./.github/workflows/sdk-nightly-tests.yaml
    with:
      learning_parameter_settings: default
    secrets:
      SC_HOST: ${{ secrets.SC_HOST }}
      SC_USERNAME: ${{ secrets.SC_USERNAME }}
      SC_PASSWORD: ${{ secrets.SC_PASSWORD }}
