# This is a basic workflow that is manually triggered

name: SDK tests

# Controls when the action will run. This action can be triggered manually (workflow_dispatch trigger), and it will be run automatically when a PR to main is made.
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main 
  

jobs:
  build:
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        python-version: ['3.8']
    steps:
      - name: Checkout code using caching for Git LFS
        uses: nschloe/action-cached-lfs-checkout@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
          pip install -r requirements-deployment.txt
          pip install -r tests/requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=88 --statistics
      - name: Test with pytest
        run: |
          pytest tests -c tests/offline.ini --cov=sc_api_tools 
