# This is a basic workflow that is manually triggered

name: SDK PR tests

# Controls when the action will run. This action can be triggered manually
# (workflow_dispatch trigger), and it will be run automatically when a PR to main is made.
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main 

env:
  INTEGRATION_TEST_REPORT: integration_test_report.html

jobs:
  build:
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9']
    steps:

      - name: Checkout code with caching for Git LFS
        uses: nschloe/action-cached-lfs-checkout@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package with deployment and test requirements
        run: |
          python -m pip install --upgrade pip
          pip install ".[deployment,tests]"

      - name: Flake8 linting
        run: flake8 .

      - name: Pydocstyle linting
        run: pydocstyle sc_api_tools --count

      - name: Test with pytest
        run: |
          pytest tests/integration -c tests/offline.ini --cov=sc_api_tools --html=$INTEGRATION_TEST_REPORT --self-contained-html

      - name: Upload test report for integration tests
        # Publish the integration test report to github
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: integration-test-report
          path: ${{ env.INTEGRATION_TEST_REPORT }}
