name: "Security scan"

on:
  schedule:
    # Run security checks every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - "releases/**"

permissions: {} # No permissions by default

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Needed to upload the results to code-scanning dashboard
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run Semgrep scan
        id: semgrep
        uses: open-edge-platform/geti-ci/actions/semgrep@ca665c838e20394cebea11229217f6282a9ab27b
        with:
          scan-scope: "all"
          output-format: "sarif"
          severity: "LOW"
          fail-on-findings: true
